# Examining Racial Discrimination in the US Job Market

### Background
Racial discrimination continues to be pervasive in cultures throughout the world. Researchers examined the level of racial discrimination in the United States labor market by randomly assigning identical résumés to black-sounding or white-sounding names and observing the impact on requests for interviews from employers.

### Data
In the dataset provided, each row represents a resume. The 'race' column has two values, 'b' and 'w', indicating black-sounding and white-sounding. The column 'call' has two values, 1 and 0, indicating whether the resume received a call from employers or not.

Note that the 'b' and 'w' values in race are assigned randomly to the resumes when presented to the employer.

<div class="span5 alert alert-info">
### Exercises
You will perform a statistical analysis to establish whether race has a significant impact on the rate of callbacks for resumes.

Answer the following questions **in this notebook below and submit to your Github account**. 

   1. What test is appropriate for this problem? Does CLT apply?
   2. What are the null and alternate hypotheses?
   3. Compute margin of error, confidence interval, and p-value.
   4. Write a story describing the statistical significance in the context or the original problem.
   5. Does your analysis mean that race/name is the most important factor in callback success? Why or why not? If not, how would you amend your analysis?

You can include written notes in notebook cells using Markdown: 
   - In the control panel at the top, choose Cell > Cell Type > Markdown
   - Markdown syntax: http://nestacms.com/docs/creating-content/markdown-cheat-sheet


#### Resources
+ Experiment information and data source: http://www.povertyactionlab.org/evaluation/discrimination-job-market-united-states
+ Scipy statistical methods: http://docs.scipy.org/doc/scipy/reference/stats.html 
+ Markdown syntax: http://nestacms.com/docs/creating-content/markdown-cheat-sheet
</div>
****

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
data = pd.io.stata.read_stata('us_job_market_discrimination.dta')

In [3]:
# number of callbacks for black-sounding names
sum(data[data.race=='b'].call)

157.0

In [12]:
data.head(25)

,id,ad,education,ofjobs,yearsexp,honors,volunteer,military,empholes,occupspecific,...,compreq,orgreq,manuf,transcom,bankreal,trade,busservice,othservice,missind,ownership
0,b,1,4,2,6,0,0,0,1,17,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
1,b,1,3,3,6,0,1,1,0,316,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
2,b,1,4,1,6,0,0,0,0,19,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,b,1,3,4,6,0,1,0,1,313,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,b,1,3,3,22,0,0,0,0,313,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
5,b,1,4,2,6,1,0,0,0,266,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
6,b,1,4,2,5,0,1,0,0,13,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
7,b,1,3,4,21,0,1,0,1,313,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
8,b,1,4,3,3,0,0,0,0,316,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
9,b,1,4,2,6,0,1,0,0,263,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
10,b,1,4,4,8,0,1,0,1,379,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
11,b,1,4,4,8,0,0,0,0,316,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
12,b,1,4,4,4,0,0,0,1,27,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Private
13,b,1,4,2,4,0,0,0,0,21,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Private
14,b,1,4,2,5,0,1,0,0,263,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,
15,b,1,1,3,4,0,0,0,0,316,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,
16,b,1,4,3,5,0,1,0,0,268,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,
17,b,1,4,3,6,0,0,0,0,267,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,
18,b,1,4,2,6,1,1,0,0,266,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
19,b,1,2,2,8,0,0,0,1,265,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
20,b,1,4,3,4,0,1,0,0,316,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
21,b,1,4,3,3,0,0,0,0,317,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
22,b,1,2,2,2,0,0,0,0,265,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,
23,b,1,4,3,7,0,0,0,1,313,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
24,b,1,4,3,3,0,1,0,0,316,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,

## 1) What test is appropriate for this problem? Does CLT apply?

The chi-squared test is most appropriate to test for a  relationship between two categorical variable, which race and call-back both are. Central limit theorem does still apply to binomial distributions.

## 2) What are the null and alternate hypotheses?

The null hypothesis is that there is no statistical relationship between race and call-backs and the alternate is that there is a relationship. I will use an alpha of 0.05.

## 3) Compute margin of error, confidence interval, and p-value.

In [5]:
contingency_table = pd.crosstab(data.race, data.call)
contingency_table.columns = ['No','Yes']
contingency_table.index = ['Black','White']
contingency_table

         No  Yes
Black  2278  157
White  2200  235

In [6]:
stats.chi2_contingency(contingency_table)

(16.449028584189371, 4.9975783899632552e-05, 1, array([[ 2239.,   196.],
        [ 2239.,   196.]]))

The p-value of 0.0000499 is below our alpha threshold. We can reject the null hypothesis and conclude that race is related to call-back.

I am doing question 5 before question 4, because I cant write the "story" until I have answered question 5.

## 5) Does your analysis mean that race/name is the most important factor in callback success? Why or why not? If not, how would you amend your analysis?

No. P-values dont do this; they dont show which variable is 'most important'. I can perform multiple chi-squared tests to show which variables are related to call back, but comparing p-values still wont give an understanding of which is more important than the others. 

Lets try a few other variables.

In [23]:
contingency_table = pd.crosstab(data.education, data.call)
contingency_table.columns = ['No','Yes']
contingency_table

             No  Yes
education
0            43    3
1            37    3
2           249   25
3           922   84
4          3227  277

In [24]:
stats.chi2_contingency(contingency_table)

(0.81003202023338983,
 0.93709809446278336,
 4,
 array([[  4.22973306e+01,   3.70266940e+00],
        [  3.67802875e+01,   3.21971253e+00],
        [  2.51944969e+02,   2.20550308e+01],
        [  9.25024230e+02,   8.09757700e+01],
        [  3.22195318e+03,   2.82046817e+02]]))

In [25]:
contingency_table = pd.crosstab(data.empholes, data.call)
contingency_table.columns = ['No','Yes']
contingency_table

            No  Yes
empholes
0         2519  169
1         1959  223

In [26]:
stats.chi2_contingency(contingency_table)

(24.639055771222285,
 6.9136265035402292e-07,
 1,
 array([[ 2471.63531828,   216.36468172],
        [ 2006.36468172,   175.63531828]]))

## 4) Write a story describing the statistical significance in the context or the original problem.

From the above analyses, we can see that years of education did not have a significant relationship with call-back, but employment holes and race do. However, simple because the p-value for employment holes (0.000000691) is smaller than the p-vaue for race (0.0000499) by several orders of magnitude, does not mean it is a more influencial variable. the best way to determine the most important factor in a system is to develop a model and determine the change in R-squared value when each factor is added. The change in R suqared due to each varable shows how much variance is explained by each. However, the building of such a model is beyond the scope of this mini-project. 

For now, I believe that it is enough to say that *some* factors, including race, influence call-back. Since the assignment of race to applications through 'black-sounding names' was done randomly and distributed equally among high and low quality resumes, we can conclude that racial discrimination is a significant factor in call-backs.